[project]
name = "mongodb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "google-genai>=1.46.0",
    "ipykernel>=7.1.0",
    "pip>=25.3",
]
